application: maniac787
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
#- url: /favicon.ico
#  static_files: favicon.ico
#  upload: favicon.ico

- url: /templates/css
  static_dir: templates/css

- url: /templates/js
  static_dir: templates/js

- url: /templates/images
  static_dir: templates/images

- url: .*
  script: plantilla.application